version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "nightly"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/backend"
  target-branch: "nightly"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/packages/client"
  target-branch: "nightly"
  schedule:
    interval: daily
